### ISSUE TITLE
Issue on Windows 

### ISSUE THREAD

**Issue by volkanunsal** [cldwalker/boson#4]
I get this error when I run a simple boson command on a Windows machine.

...pbox\Tools\System\Console2> boson libraries
Error: marshal data too short

Tried searching for it, but had no luck with it.

**Comment by cldwalker** [comment]
I don't have windows but I'll see what I can do.
Could you give me a verbose dump of the error?: boson -v libraries
What ruby version are you running?

**Comment by volkanunsal** [comment]
Here you go:

(I'm using ruby 1.8.6 (2008-08-11 patchlevel 287) [i386-mswin32])

EDIT: moved the error code to Gist

http://gist.github.com/273908

EDIT2: My operating system is Windows 7, build 7100.

**Comment by cldwalker** [comment]
Ok. I have a potential fix on this branch: http://github.com/cldwalker/boson/tree/windows
Since I don't have windows, I'll need you to test the fix.

If you can run git and rake on your machine, here's a series of commands to checkout that branch, build the boson gem and reinstall it:
- git clone git://github.com/cldwalker/boson.git
- cd boson/
- git checkout --track -b windows origin/windows
- rake gemspec
- rake install

If you can't, then you'll need modifying boson's source with this commit: 1861e54c21594cbf3a11633ed978a148ac70247b

To test that the new boson works, first delete the old corrupt index at ~/.boson/config/index.marshal. Making sure you're not in a directory with any local boson files (i.e. your home directory), run a boson command i.e. `boson libraries`

Hopefully this works :) Let me know.

**Comment by volkanunsal** [comment]
I'm not sure why, but my response didn't show up here. :-/

So I copied the fixes by hand and it seemed to work. Yay! Thanks.

Are you going to include this fix in the next release? Or is it Windows-only?

**Comment by cldwalker** [comment]
Glad it worked! It'll come out in the next release. Hopefully this week.

**Comment by cldwalker** [comment]
Fix finally released with 0.2.2. Let me know if there are more issues with this.
