### ISSUE TITLE
Not enough simple examples.

### ISSUE THREAD

**Issue by yb66** [cldwalker/boson#50]
Hi,

Boson looks like an incredible project, but if I may give some constructive criticism, the examples aren't very helpful. It's one thing to point to working libraries like boson-more or vimdb as examples, but they are _far too complex_ for getting started with. Since you take time to compare with Thor, the [What Is Thor page](http://whatisthor.com/) gives a very good example, that is just a toy, but tells you everything you need to know, including subcommands. If I wanted to implement something similar with Boson… erm, too difficult already.

Sorry if that sounds harsh, but I came here because of the limitations of Thor but I'll end up rolling my own because Thor isn't powerful enough and I've spent too long looking at API docs that don't give examples.

As a specific example, [Writing Plugins](https://github.com/cldwalker/boson#writing-plugins) is good. It shows how to extend `start` without mentioning _why_ I'd ever want to do that or give an example of where that might be useful. It states "Any methods that are defined in an API or APIClassMethods module are extendable." and yet a search of the docs gives 3 different `start` methods and 9 different `API` classes. Which one would I start with? I've no idea looking through them - why BareRunner instead BinRunner…? Then the link is given to boson-more, which is to jump from having no knowledge (which is why I'll be reading docs) to advanced straight away. I look through the source and it makes little sense.

Along with a lot of documentation floating around the internet that seems to be out of date, it seems like a missed opportunity.

I hope you understand that I say this with the best of intentions and only wish to highlight something that may not be obvious to you as the author, and may have occurred to others who have not bothered to mention anything.

Regards,
Iain

**Comment by cldwalker** [comment]
Thanks for the feedback. You've made some good points but unfortunately there's too much functionality to have a good example for everything. Also, thor has dozens of maintainers and is used actively by the rails community (28 M downloads) while I'm a solo developer with dozens of projects to maintain. When I get some time I'll update some of the docs.  To address some of your specific points:
- When you say vimdb is too complicated, is it because you can't find where it uses boson? Would it help if I [directly linked](https://github.com/cldwalker/vimdb/blob/master/lib/vimdb/runner.rb#L20-L25) to an example? That particular subcommand isn't hard to read and reads almost exactly as thor and rake.
- Some of the docs on the internet i.e. on my website, tagaholic.me,  are out of date. I've stopped pointing to it and now point to the always up-to-update [rdoc.info](http://rdoc.info/gems/boson).
