### ISSUE TITLE
More flexible browser method in web_core.rb

### ISSUE THREAD

**Issue by michaelbarton** [cldwalker/boson#6]
I've tried piping the output of commands to the browser method in webcore but I get this error:

```
Error: can't convert Array into String
```

I think this is because my boson command returns an array of hashes. I've tried to play with the browser method so that it will still open simple strings but also deal with an array of hash objects as long as each hash contains a ":url" key.

Please see my commit - http://bit.ly/bmrUqx

Thanks, Mike

**Comment by cldwalker** [comment]
Since boson commands all share the same namespace by default, it's easy to override any command by passing its library a :force atttribute: http://gist.github.com/290074 . 

If you want to only override browser() sometimes than load it on the commandline:
    boson -l=my_core pubmed ...

If you always want to have your browser() loaded then configure boson to load this library to be a default one by putting it under the :defaults key of ~/.boson/config/boson.yml i.e.: http://github.com/cldwalker/irbfiles/blob/master/boson/config/boson.yml#L3

You may be interested to know that in the next release, there will be stronger support for pipe options. In particular I have a menu pipe library which makes it dead easy to pick text out of any cell of a table and call a command on it. Very handy for chaining commands interactively

**Comment by michaelbarton** [comment]
Thanks for your comments they are useful and interesting. Is there a way to config my own browser method to be only used with specific boson commands? I guess there is but I'm still learning how to use boson.

I like the sound of your piping library for the next release. The idea for my commit was boson commands seem to return hashes, so therefore if a hash was passed the browser method would understand this and open it. Something along the lines of duck typing ...

**Comment by cldwalker** [comment]
If you don't want to override browser() globally then I'd recommend renaming it. Either way, you can specify a library's dependency by passing a :dependencies attribute to a library's config. [Example](http://github.com/cldwalker/irbfiles/blob/master/boson/commands/public/site/misc.rb) and [docs](http://tagaholic.me/boson/doc/classes/Boson/Library.html#M000105).

I'm not sure why you're trying to change browser() but it sounds like you want it to handle hashes when you pipe something to it. If so, I'd recommend making a custom pipe option. [Docs](http://tagaholic.me/boson/doc/classes/Boson/Pipe.html) and [example](http://github.com/cldwalker/irbfiles/blob/master/boson/config/boson.yml#L283)

**Comment by cldwalker** [comment]
Boson's latest release can use the menu pipe I talked about. You can read about it at http://tagaholic.me.

I'm assuming you've worked this issue out.

**Comment by michaelbarton** [comment]
Yes that's great. I've just implemented that now
http://github.com/michaelbarton/pubmed-boson/commit/621b5102073342f2662848821aca58c1587fafcb
